file = open("spider.txt")

#When we open a file, like we're doing in this example, the operating system checks that we have permissions to access that file and then gives our code a file descriptor.
#This is a token generated by the OS that allows programs to do more operations with the file.
#In Python, this file descriptor is stored as an attribute of the files object. The file object gives us a bunch of methods that we can use to operate with the file.
#Now, with this file object, we can read the contents of the file and print them to the screen.

print(file.readline())
# ooo itsy bitsy spider climbed up the waterspout.
print(file.readline())
# Down came the rain - this is the second line - this due to readline reading line by line and showing you next line every time you type it

print(file.read())
# Both readline() and read() start from the current position. readline() reads just one line, while read() reads until the end of the file.

file.close() # this will close the file - this can be annoying or something that cause errors as you would have to keep track of whats open and whats closed

# When we use a "with" block, Python will automatically close the file. So we don't need to remember to do that ourselves.
with open("spider.txt") as file:
    print(file.readline())